import { dir } from 'i18next';
import { languages } from '../i18n/settings';

import { Inter } from 'next/font/google';
import './globals.css';
import 'animate.css';
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata = {
  title: 'FinDigit',
  description: 'Generated by create next app',
};

const RootLayout = ({ children, params: { lng } }) => {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={inter.className}>
        <Navbar lng={lng} />
        {children}
        <Footer lng={lng} />
      </body>
    </html>
  );
};
export default RootLayout;
